### ISSUE TITLE
easystats not installing

### ISSUE THREAD

**Issue by Kbs21** [easystats/easystats#164] opened 2021-07-20 11:37 UTC
Hey, I try running the code to install easystats : install.packages("easystats", repos = "https://easystats.r-universe.dev") but it shows error : 

```r
Error: package or namespace load failed for 'easystats':
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: NULL
  error: package or namespace load failed for 'effectsize':
 object 'check_heterogeneity' is not exported by 'namespace:parameters'
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'easystats':
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: NULL
  error: package or namespace load failed for 'effectsize':
 object 'check_heterogeneity' is not exported by 'namespace:parameters'
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/....'
Warning in install.packages :
  installation of package ‘easystats’ had non-zero exit status
```

Can someone please help fixing this

**Comment by IndrajeetPatil** [comment] 2021-07-20 11:42
Hi, sorry for the trouble. `easystats` ecosystem is currently undergoing a bit of restructuring, and this is the reason why you can't download the packages (you'll have to wait until https://github.com/easystats/effectsize/pull/361 is merged).

For now, we would recommend downloading the needed packages from CRAN.

**Comment by Kbs21** [comment] 2021-07-20 11:46
Ohh, okay thanks, till when can I expect this would be done and easystats will work

**Comment by IndrajeetPatil** [comment] 2021-07-22 06:42
This should work now.

```r
 install.packages("easystats", repos = "https://easystats.r-universe.dev")
```

**Closed by IndrajeetPatil** 2021-07-22 06:42 UTC
Labels: question :question:

**Comment by Kbs21** [comment] 2021-07-22 12:08
it's still not installing, showing the same error

**Comment by strengejacke** [comment] 2021-07-22 12:15
I _think_ you have to install once the single packages manually first:

` install.packages(c("insight", "datawizard", "parameters", ...) , repos = "https://easystats.r-universe.dev")`

then `install.packages("easystats", repos = "https://easystats.r-universe.dev")` should work. I guess this is due to moving some functions around, which causes the namespace errors.

**Comment by IndrajeetPatil** [comment] 2021-07-22 12:16
Here is a reproducible example that this works:

``` r
install.packages("easystats", repos = "https://easystats.r-universe.dev")
#> Installing package into '/Users/patil/Library/R/x86_64/4.1/library'
#> (as 'lib' is unspecified)
#> 
#> The downloaded binary packages are in
#>  /var/folders/_p/55p16nb13cs7yy707d8l_v1s_rmpr4/T//RtmpmDNlmU/downloaded_packages
```

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment] 2021-07-22 13:11
> Here is a reproducible example that this works:

Have you tried this with all other easystats packages *not* being installed?
